name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - master
    - develop

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "pypy3"]

    name: Python ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install python tools
      run: python -m pip install -r literary oldest-supported-numpy scipy matplotlib

    - name: Build
      run: python -m pip install .

    - name: Test
      run: python -m jupyter run tests/*.ipynb
